spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

flyway:
  enabled: true
  locations: classpath:db/migration

server:
  port: ${PORT:8084}

